# Generated by Django 4.0.4 on 2022-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/directors')),
                ('fullname', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='lastname',
        ),
    ]
