# Generated by Django 4.0.4 on 2022-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_director_rename_firstname_actor_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='director_movies', to='movies_app.director'),
        ),
    ]
